import './globals.css'
import Sidebar from '@/components/sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col sm:flex-row bg-[url('https://img.freepik.com/free-vector/hand-painted-watercolor-pastel-sky-background_23-2148902771.jpg?w=2000')]">
      <Sidebar/>


        <main className='grow-full p-16 w-full sm:basis-2/3 ml-auto'>{children}</main>
      </body>
    </html>
  )
}
